DEFAULT_STORAGE_PROTOCOL = 'http'
DEFAULT_STORAGE_HOST = 'localhost'
DEFAULT_STORAGE_PORT = 5000
DEFAULT_STORAGE_PATH = '/'

DEFAULT_STORAGE_URI = '{proto}://{host}:{port}{path}'.format(
	proto=DEFAULT_STORAGE_PROTOCOL,
	host=DEFAULT_STORAGE_HOST,
	port=DEFAULT_STORAGE_PORT,
	path=DEFAULT_STORAGE_PATH)
